### ISSUE TITLE
huesyncbox.set_sync_state gives error on input

### ISSUE THREAD

**Issue by K-RAD** [mvdwetering/huesyncbox#15]
huesyncbox.set_sync_state
entity_id: media_player.philips_hue_hdmi_sync_box
input: "hdmi2"

Gives me `Failed to call service huesyncbox/set_sync_state. value is not allowed for dictionary value @ data['input']
`
What am I missing?

**Comment by K-RAD** [comment]
I just had a look through the code and it's supposed to be input2 not hdmi2. The documentation is wrong

**Comment by mvdwetering** [comment]
Actually this is a leftover from a long time ago when the sources exposed by the mediaplayer were hdmi1, hdmi2, etc... 
At some point I decided it was more clear to use the names as set on the syncbox so instead of hdmi1 it would be "DVD Player" or whatever you set in the syncbox configuration. 
I did not update this service it seems.

I think the "input" attribute should take the same values as the sources available in the media_player and I should actually also rename "input" to "source" to make that consistent.

**Comment by mvdwetering** [comment]
So it seems I confused myself in the last comment. I got the input in the `set_sync_state` (which needs to have a fixed name) confused with the `select_source` service of the `media_player` which uses the userdefined name.

So indeed it was only a documentation update which is now done (with some other service related fixes) in release 1.12.0.
