### ISSUE TITLE
device not loaded, likely due to HA updates

### ISSUE THREAD

**Issue by mxia9416** [mvdwetering/huesyncbox#98]
**Describe the bug**
Device not loaded after starting HA, it's likely due to the newer version of HA as it was the only change I made recently.

**To Reproduce**
1. Go to 'Device and services'
2. Click on 'Philips Hue Play HDMI Sync Box'
3. See error 'Device not loaded'

**Expected behavior**
Load device successfully.

**Diagnostics**
If possible add diagnostics data from HA. The "Download diagnostics" option can be found in the vertical 3 dots menu (⋮) of the integration.

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
Error occurred loading flow for integration huesyncbox: No module named 'aiohuesyncbox'

**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: 2024.5.5
- Home Assistant operating environment (OS/Container/Supervised/Core): OS
- Huesyncbox integration version: 2.1.0
- Last working version (if known): 2.1.0

**Additional info**
Download diagnostics was not available in my case, it was missing from the drop-down menu. I found an error in logging that may imply the cause.

**Comment by mvdwetering** [comment]
That is a very strange error to get. Aiohuesyncbox is the library used by the integration for the actual comuinication with the syncbox. It should get installed automatically by Home Assistant. It is also strange that it used to be there (because it was working) and now it is gone.

Not sure what to suggest other then trying to restart Home Assistant which you might have already tried.
Otherwise maybe redownload the integration. There is an option in HACS if you are using that.

**Comment by mxia9416** [comment]
Redownloading the integration from HACS solved the problem, Thanks! I'll close the issue.
